# U-Net Segmentation Configuration
model:
  name: 'unet'
  in_channels: 3
  out_channels: 1
  base_filters: 64

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler:
    name: 'reduce_on_plateau'
    patience: 5
    factor: 0.5
  loss:
    name: 'combined'
    weights:
      bce: 0.5
      dice: 0.5

data:
  image_size: [256, 256]
  augmentation:
    horizontal_flip: true
    vertical_flip: true
    rotation_range: 45
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]

optimization:
  pruning:
    method: 'l1_unstructured'
    amount: 0.3
  quantization:
    method: 'dynamic'
    dtype: 'qint8'
